import React from "react";

import "./termsandcondition.css"

const TermsandCondition = () => {
  return (
    <div>
      <div className="terms">
        <h4 className="terms-h4">Terms and Condition</h4>
        <p className="terms-p">
          This document is an electronic record in terms of Information
          Technology Policy, 2057 and rules there under as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Policy, 2057. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures. This document is published
          in accordance with the provisions of Rule 3(1) of the Information
          Technology (Intermediaries guidelines) Rules, 2057 that require
          publishing the rules and regulations, privacy policy and Terms of Use
          for access or usage of www.kinkhel.com website and mobile app. The use
          of any product, service or feature (the “Materials”) available through
          kinkhel.com (hereinafter referred to as “Website”) a company
          incorporated under the Companies Act, 2063 with its registered office
          at Kathmandu, Nepal (hereinafter referred to as “kinkhel.com”). For
          the purpose of these Terms of Use, wherever the context so requires
          “You” or “User” shall mean any natural or legal person who visits or
          uses the Website. Kinkhel allows the User to surf the Website without
          registering on the Website. The term “We”, “us”, “Our” shall mean
          Oneness International Private Limited. Your use of the Website and
          services and tools are governed by the following terms and conditions
          (“Terms of Use”) as applicable to the Website including the applicable
          policies which are incorporated herein by way of reference. Use of the
          Website shall subject you to the policies that are applicable to the
          Website. By mere use of the Website, You shall be contracting with
          Oneness International Private Limited and these terms and conditions
          including the policies constitute your binding obligations, with
          kinkhel.com. This Website, including all Materials present is the
          property of Oneness International Pvt. Ltd., and is copyrighted and
          protected by worldwide copyright laws and treaty provisions. You
          hereby agree to comply with all copyright laws worldwide in your use
          of this Website and to prevent any unauthorized copying of the
          Materials. kinkhel.com does not grant any express or implied rights
          under any patents, trademarks, copyrights or trade secret information.
          When you use any Materials provided by us through the Website
          including but not limited to (e.g. customer comments and social
          actions) you will be subject to the rules, guidelines, policies, terms
          and conditions applicable to such services and they shall be deemed
          incorporated into the Terms of Use and considered a part and parcel of
          the Terms of Use. We reserve the right, at our sole discretion, to
          change, modify, add, or remove portions of the Terms of Use at any
          time and without any prior written notice to you. It is your
          responsibility to review the Terms of Use periodically for
          updates/changes. Your continued use of the Website following the
          changes will mean that you accept and agree to the revisions. As long
          as you comply with the Terms of Use, we grant you a personal,
          non-exclusive, non-transferable, and limited privilege to enter and
          use the Website. Accessing, Browsing or otherwise using the website
          indicates your agreement to all the terms and conditions under these
          terms of use, so please read the terms of use carefully before
          proceeding. By impliedly or expressly accepting these Terms of Use,
          you also accept and agree to be bound by kinkhel.com Policies
          (including but not limited to Privacy Policy available on Privacy
          Policy as amended from time to time.
        </p>
      </div>
     
    </div>
  );
};

export default TermsandCondition;
